### PR TITLE
Constrain pipeline to Flutter 2.0.6

### PR DESCRIPTION
**Pull request by elKei24**
This should fix the failing tests. On the long term, we should of course update to the latest version.

### CODE REVIEW

**Comment by RoAnBu** [comment]
@elKei24 same fix for ios necessary?

**Comment by elKei24** [comment]
> @elKei24 same fix for ios necessary?

Yes, would be, but seems not possible unfortunately. The OSX images are only selectable by Xcode version, and are always created with the latest version of flutter (can be seen [here](https://github.com/cirruslabs/osx-images/blob/master/templates/xcode.json)).

The best would probably be to update to the latest version as fast as possible. I tried to do it (s. branch `update-dependencies`), but it does not build any more with the latest MapboxGL lib: `SDK Registry token is null. See README.md for more information.` I had a look at the Readme and tried to set the key(s), but without success.

**Comment by RoAnBu** [comment]
ok maybe just ignore ios build for now?

**Review by RoAnBu — APPROVED** [review]

**Comment by elKei24** [comment]
> ok maybe just ignore ios build for now?

I think so, yes. At least allows us to merge your artifact PR.

**Pull request merged**
