### PR TITLE
#51 bring camera to click location

### LINKED ISSUE #51: Center selected accepting business when clicked
Accepting criteria:
* [x] map centers an accepting business when its summary is shown

Belongs to #49.

### PR DESCRIPTION
**Pull request by elKei24**
Closes #51

### CODE REVIEW

**Comment by elKei24** [comment]
Blocked: can not test it until BE delivers data again

**Review by RoAnBu — COMMENTED** [review]
@elKei24 centering is not really working, the map just moves a little bit and does not really center. Tested on the Android emulator.

Also the detail loading is not always working, sometime it's just stuck in the loading animation

**Comment by elKei24** [comment]
> centering is not really working, the map just moves a little bit and does not really center. Tested on the Android emulator.

Yeah that might be, I could not test it yet due to missing data.


> Also the detail loading is not always working, sometime it's just stuck in the loading animation

Hm, I had also noticed this, but thought that this is caused by an non-responding backend. I will check that, but not as part of this technical task.

**Comment by elKei24** [comment]
>  centering is not really working, the map just moves a little bit and does not really center. Tested on the Android emulator.

Should be fixed now. No idea if this is seen as a feature by map box that they do not move the camera too far if the destination already is inside the viewport, but renouncing the movement animation “fixes” it.

**Review by RoAnBu — APPROVED** [review]

**Pull request merged**
