### PR TITLE
#150 allow icon overlap

### LINKED ISSUE #150: Accepting stores hidden if close to each other
**Describe the bug**
If there are multiple accepting stores close to each other, some of them are not visible until zooming in further.

**Expected behavior**
The accepting stores should either be clustered like on lower zoom levels, or should just all be shown, even if they overlap (preferred).

**Screencast**
screencast

**Additional context**
Possibly related to #141.

### PR DESCRIPTION
**Pull request by elKei24**
Set `"icon-allow-overlap": true` for `physical_stores` layer to close #150.

Additional improvements:
- Changed map language to German
- Adapted map style to app design

grafik

### CODE REVIEW

**Comment by maxammann** [comment]
Looks very nice!

**Comment by maxammann** [comment]
Why are there that many reformatting changes? makes it pretty much impossible to review

**Comment by elKei24** [comment]
> Why are there that many reformatting changes? makes it pretty much impossible to review

I used the maputnik GUI editor to edit it, and it exported it like that 😕

**Review by maxammann — APPROVED** [review]
ok weird :D for me it created clean diffs

**Pull request merged**
